### ISSUE TITLE
electron - quick options don't work correctly in preview

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#101]
<a href="https://github.com/Subliminalman"><img src="https://avatars1.githubusercontent.com/u/1288980?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Subliminalman](https://github.com/Subliminalman)**
_Tuesday Aug 27, 2019 at 00:27 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/101_

----

For the preview mode within the electron yarn app (version 0.3.6) on OSx  (haven't tried other platforms yet) it doesn't handle quick selections correctly. It will display the options but when it won't show the result. Rather it will hang on the selection, not show the result, then you have to select from the options again then it will go further into the script.

Here is the script I was testing with.

```
This is a test for writing

->Heya
    Howdy
->Heeeeya
    Wow
->Bye
    Goodbye

Meowdy
[[Barkdy|Bark]]
[[Meowdy|Meowdy]]

```
Here is the result from the script above.

![Screen Shot 2019-08-26 at 6 25 28 PM](https://user-images.githubusercontent.com/1288980/63731877-05edcf00-c82f-11e9-834d-c8abaa8d2465.png)

The expected result would be 

This is a test for writing
[select Heeeeya]
Howdy
Wow

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Tuesday Aug 27, 2019 at 05:27 GMT_

----

This is a known bondagejs bug that keeps getting filed here. I might try to
make a fix for bondagejs and update the library in yarn at some point

**Comment by blurymind** [comment]
I have disabled previewing temporarily. It's dependency on electron needs to be scrapped and the preview should be refactored to appear in the same window. The bug here needs to be addressed in bondagejs

**Comment by blurymind** [comment]
Btw they will work if you ad a space between the -> and the lines

**Comment by blurymind** [comment]
do
This is a test for writing
```
-> Heya
    Howdy
-> Heeeeya
    Wow
-> Bye
    Goodbye

Meowdy
[[Barkdy|Bark]]
[[Meowdy|Meowdy]]
```

instead of

```
This is a test for writing

->Heya
    Howdy
->Heeeeya
    Wow
->Bye
    Goodbye

Meowdy
[[Barkdy|Bark]]
[[Meowdy|Meowdy]]
```

**Comment by desplesda** [comment]
+1 for "meowdy".

**Comment by FaultyFunctions** [comment]
Related to #199.  This one has been inactive for a while. Closing this one, but refer to the other issue for more information.
