### ISSUE TITLE
[CLOSED] Wrong carriage position

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#102]
<a href="https://github.com/roxygen"><img src="https://avatars2.githubusercontent.com/u/3707285?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roxygen](https://github.com/roxygen)**
_Monday Sep 16, 2019 at 05:04 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/102_

----

Hi! I tried to build/run application and got this problem with carriage. It placed with big offset from real one.

![image](https://user-images.githubusercontent.com/3707285/64935141-94c39980-d879-11e9-9fdf-2f57d2f94255.png)
![image](https://user-images.githubusercontent.com/3707285/64935166-c9375580-d879-11e9-914a-03b57779a34d.png)

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Monday Sep 16, 2019 at 06:02 GMT_

----

Hi Roxy, this is a problem with ace editor which yarn uses, I thought I had
fixed. Are you running it on Windows or Mac?

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Monday Sep 16, 2019 at 12:49 GMT_

----

Thank you for reporting this regression. It is fixed now via https://github.com/InfiniteAmmoInc/Yarn/commit/a4db7ee65368f3cf2d32cceebe8a84919d153e2b

Feel free to reopen if the issue persists for you

**Comment by roxygen** [comment]
Thank you!
