### ISSUE TITLE
Making yarn work on mobile

### ISSUE THREAD

**Issue by blurymind** [YarnSpinnerTool/YarnEditor#106]
Yarn can now be partially used on mobile - as a progressive web app (https://developers.google.com/web/progressive-web-apps)

It can be accessed here:
https://yarnspinnertool.github.io/YarnEditor/
it can be installed on android/ios by selecting "Add to home screen" with chrome. This will add it to the home screen and when launched from there - make it work in full screen without the annoying address bar taking up so much space.

I got the localhost to work on mobile, got the layout to scale well in portrait mode,
There are still things that need addressing before it can be usable:
- [x] Add support for mobile layout
- [x] Add manifest.json (webapp) and update webpack's settings
- [x] Yarn's home screen icon is not working yet for some reason (potentially because its not png and right size)
- [x] Touch input doesnt work on changing color of nodes, moving them, deleting them or panning the screen
- [x] Dropbox I/O needs implementing to be able to easily sync files between yarn mobile and yarn desktop
- [x] Offline caching via a webworker needs to be implemented to get the installed yarn on home screen to also work when the device is offline
- [ ] fix: Moving a node via touch after panning moves the node, but also moves other nodes

**Comment by desplesda** [comment]
This is awesome!!

**Comment by blurymind** [comment]
Touch works now. Dropbox is underway

**Comment by blurymind** [comment]
Got dropbox I/O to work now - both saving and loading

**Comment by blurymind** [comment]
much thanks for the fantastic work that @JamesAndrewJackson13 did to implement the offline worker and fix the icon not working. This is complete now!

Yarn editor is almost mobile ready. I will add some new checkboxes to add to make it perfect for mobile though :)

If you feel like taking on it,please submit another pr

**Comment by blurymind** [comment]
I will close this for now, as it is already working on mobile. There are still some touch input quirks to clear up, but they are not really breaking it on mobile
