### ISSUE TITLE
CANT DOWNLOAD

### ISSUE THREAD

**Issue by ghhjklkljlkjlkjkl** [YarnSpinnerTool/YarnEditor#109]
Can someone please help me? The link to the windows and mac build is broken and I cannot find anywhere to download the installer.

**Comment by desplesda** [comment]
The installers haven’t yet been transferred to this new repo, but we maintain a web version of the editor here: https://yarnspinnertool.github.io/YarnEditor/

**Comment by ghhjklkljlkjlkjkl** [comment]
Oh okay, thank you. Do you know how long it will take?

**Comment by blurymind** [comment]
Ideally we want to get some sort of an autobuild system for the electron editor. Prs for this are very much welcome. Might give it a try when theres more time. I plan to give the electron app some more love after new year

**Comment by desplesda** [comment]
Hi! New builds for macOS and Windows have been added to the [Releases](https://github.com/YarnSpinnerTool/YarnEditor/releases/latest) page.
