### ISSUE TITLE
[web|chrome] Cant save to dropbox

### ISSUE THREAD

**Issue by digital-synapse** [YarnSpinnerTool/YarnEditor#114]
In the web app, when I select the save to dropbox option a window opens and allows me to log in to my dropbox account but when I click save i get the error "Failed to load request"

**Comment by blurymind** [comment]
Ah yes, it looks like the drobox guys have updated their API and saving is now not working.
I might need to take another look at this

**Comment by blurymind** [comment]
dropbox is now disabled on both. Closing this issue.

Will have to redo the implementation at some point
