### ISSUE TITLE
[electron|win64] save to dropbox option missing

### ISSUE THREAD

**Issue by digital-synapse** [YarnSpinnerTool/YarnEditor#115]
The web app has a dropbox option but this option appears to be missing in the electron app.

May be affected by https://github.com/YarnSpinnerTool/YarnEditor/issues/114

**Comment by blurymind** [comment]
its disabled on purpose on electron due to web technology security limitations. If someone finds a way to get it to work, a PR is very much welcome :)

**Comment by blurymind** [comment]
dropbox is now disabled on both. Closing this issue.

Will have to redo the implementation at some point
