### ISSUE TITLE
Any way to embed and integrate the editor with an existing app?

### ISSUE THREAD

**Issue by justjuank** [YarnSpinnerTool/YarnEditor#119]
Hey there,
I've been working with YarnSpinner and bondage for a while and it's been amazing.
Now I'm starting to work on some kind of editor tool for my game and I was wondering if there's a way to embed this editor in an existing web app and integrate it so that I can pass for example a json file back and forth between the editor and the app?

Thanks in advance.

**Comment by blurymind** [comment]
There is. I actually did it in gdevelop :)
Depending on how your app works, you might want to borrow some ideas from 
https://github.com/4ian/GDevelop/tree/master/newIDE/app/public/external/yarn

This contains the wrapper that lets gdevelop and yarn communicate. Another script downloads and extracts yarn-editor in that folder

**Comment by justjuank** [comment]
Ah interesting, thank you for pointing me to that source.
I actually just found a way (maybe kinda hackish) to get it to work by forking the repo, made some changes like triggering some callbacks registered from my app through the `window` object, then built and bundled the dist files into my app and loaded the editor in an iframe.
Is that ok to bundle the dist files of the editor in another app?
Unfortunately my project is in a private repo and I can't share it right now.

**Comment by blurymind** [comment]
Yes it's ok to bundle it :) if you do it without altering the source code
of yarn, it will be easier to stay up to date with it too

**Comment by daviddq** [comment]
Is this still an issue? Can it be closed?

**Comment by justjuank** [comment]
Yes sorry, I'm closing it now, thank you for the help :)
