### ISSUE TITLE
Editor allows nodes with the same id (title)

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#124]
Editor allows nodes with the same id (title). Also, copy/pasting nodes create nodes with duplicate titles.

No two nodes should share the same title since it's used as nodes' unique id.

(!) Fixing this can cause problems loading already existing stories that have duplicate titles.

**Comment by daviddq** [comment]
@blurymind You mentioned that when copying nodes we could use "CopyOf [original title]". I've locally implemented this and quickly got things like "CopyOf CopyOf CopyOf..." making the title barely readable.

What about using a different approach like "My title", "My title_1", "My title_2"... ensuring that there are no duplicate titles?

**Comment by blurymind** [comment]
appending a number would actually be better :) you are right!

**Comment by daviddq** [comment]
Currently on the node editor if I specify a title that already exists (i.e. "Start") when saving the node it will be automatically and silently renamed to "Start_2". This saves us from duplicating titles.

A different approach would be what Twinery does: warn about the duplicate and don't allow to close/save the node editor:

![image](https://user-images.githubusercontent.com/6022674/78366670-1cc48300-75c1-11ea-85d9-e726dd0939b2.png)

What would be the best approach for Yarn Editor?

**Comment by blurymind** [comment]
Lets display a message in a similar way, but I dont want to lock the user. Our message can be smarter than theirs:

"This title is used by another node, so it will be renamed to ${autotile}  when changes are applied."

**Comment by daviddq** [comment]
👏👏👏👏 I am looking forward to having it integrated 👏👏👏👏

**Comment by blurymind** [comment]
>  I am looking forward to having it integrated 
> 
> Edit: Oh man! It's already integrated...

Yep, have fun :) Don't be afraid to submit pr if you find any bugs ;)

Btw, the previewer uses bbcode parsing, so if you want to add support for html like tags, you would need to add it to the previewer too

**Comment by daviddq** [comment]
Sorry dude, I'm not able to run the passages. I must be doing something very wrong:

![norun](https://user-images.githubusercontent.com/6022674/78703476-82d74000-790a-11ea-8f06-15c1c9d2cfd3.png)

Could you point to what am I mising?

**Comment by blurymind** [comment]
oh, you have to press z to advance the dialogue. I should have put a hint about that somewhere but ran outa  time
