### ISSUE TITLE
Node titles should have no leading nor trailing spaces

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#125]
To avoid inconsistencies, node title should have no leading nor trailing spaces. This also will solve problems when bondagejs is back in place, which does not support leading and trailing spaces on links/titles

**Comment by blurymind** [comment]
didnt your pr solve this? :)

**Comment by daviddq** [comment]
Yes. I just wanted to keep issues separated, so we can discuss each issue
on its own thread. For incoming contributions I will keep issues and PR
separated to ease review and merge.

**Comment by blurymind** [comment]
thank you for doing that :) just wondering if its ok to close this one, since the pr has been merged now

**Comment by daviddq** [comment]
Absolutely!

**Comment by daviddq** [comment]
Fixed in PR #121
