### ISSUE TITLE
Browser Performance lagging significantly compared to Twinery

### ISSUE THREAD

**Issue by jonaslund** [YarnSpinnerTool/YarnEditor#126]
From quickly testing Yarn, the editor is so slow it's hard to use it. 
Wondering what the performance bottleneck is, and if there's a way to disable some heavy resources using features?

**Comment by blurymind** [comment]
I welcome a PR :) If you have a very big yarn file, would you mind sharing it? It will help us evaluate performance better

**Comment by jonaslund** [comment]
Hi

It's primarily the scrolling / dragging performane that's lagging, and this is with a yarn file consisting of 1 passage, so very small. It's in Chrome / Firefox it's performance slow. 
Couldn't work it out, as by looking at it, it's very similar to Twine, but there the performance is very snappy.

**Comment by blurymind** [comment]
Panning specifically is slow then? I havent experienced that myself, but will try to find out if there are bottlenecks somewhere

**Comment by daviddq** [comment]
@blurymind Today I've been researching on drawing arrows using SVG. I find the "node dragging" experience more pleasant and performant than current arrows. Check example below:

https://jsfiddle.net/vaq2x3ey

It's just a quick demo. Arrow colors are for debugging and there's still the need to calculate proper origin/destination points and double sided arrows.

Do you think it would make sense to replace the current arrow drawing with a this approach?

**Comment by blurymind** [comment]
demo looks cool. I would of course prefer to keep the connection style with straight lines.

If we can simplify the codebase and massively improve performance by using another way to draw the nodes, then I'm all for it.

If such a PR comes,I would like some sort of a test file that demonstrates that it is indeed being handled better than the old way. I was thinking at one point of ripping out all of our custom node rendering js and favor of hooking in https://github.com/jagenjo/litegraph.js to do that completely with webgl

**Comment by daviddq** [comment]
On the demo you can set "curvature" to 0 to achieve straight lines.

By the way, _litegraph_ looks awesome. Now I want that... 😆

I agree to codebase simplification and cleanup being a must for a long running product.

**Comment by blurymind** [comment]
its incredibly powerful and performant, as well as really actively developed.
The problem is in finding a way to safely rip out the old code, while keeping the style nearly identical to what it was.

It still bothers me a bit that we have over 2k lines of code in the app.js class

**Comment by blurymind** [comment]
@daviddq recently did some fabulous optimisations which should give you a noticeable performance boost. Can you test again with the latest version please

**Comment by jonaslund** [comment]
The snappiness has improved a lot in moving the document around and zooming in and out! There's a hint of lag in moving the nodes around as compared to Twinery, but besides that, a big improvement! 

❤️

**Comment by daviddq** [comment]
There are plans to fix the panning as well. Stay tuned!

**Comment by blurymind** [comment]
> There are plans to fix the panning as well. Stay tuned!

This could potentially fix another issue that people have complained over the years - when they pan the camera, all the node positions change and that creates a giant dif on each story edit they do.

**Comment by daviddq** [comment]
It's ready on my fork, just waiting for the current PRs to be merged 😄

It boosts panning speed a couple of magnitud orders 🚀

**Comment by blurymind** [comment]
@jonaslund the panning optimisation is now merged, so feel free to give it another try :)

**Comment by jonaslund** [comment]
Way improve, much snappy! 

A huge improvement. Interesting how much the sensation of snappiness influences the feel of a web-app, this feels very good!

Closing this issue for now.

**Comment by blurymind** [comment]
Much thanks to @daviddq for the fantastic work on yarn!
