### ISSUE TITLE
Navigating back to previously edited nodes when the nodes have been renamed results in new nodes being created

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#127]
**Version 0.4.1**

Navigating back to previously edited nodes when the nodes have been renamed results in new nodes being created.

![Captura de pantalla 2020-04-01 a las 8 37 37](https://user-images.githubusercontent.com/6495061/78058246-ea781300-737f-11ea-9cb1-a46b65679e83.gif)

There's a navigation stack in app.js (self.nodeVisitHistory) that keeps track of the visited nodes' titles. To avoid this problem:

A) When renaming a node, traverse self.nodeVisitHistory stack and change the affected title there too.

or

B) self.nodeVisitHistory should keep references to the nodes instead of their titles. This may result in problems when navigating back to a node that has been deleted. We should ensure that the node still exists. If not, navigate to previous.

**Comment by blurymind** [comment]
Thank you for adding it to the  issue tracker :)
