### ISSUE TITLE
Copy/Paste  is broken in master

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#128]
**Version: 0.4.1**

**Current behavior**
When copying a node with ctrl+c ctrl+v the resulting node seems to be referencing the original. My bet is that the new object is not deep-cloned and some/all references to the original node are kept. Also probably related with knockout observables.

![copyPasteBroken](https://user-images.githubusercontent.com/6022674/78074365-ee695c80-73a2-11ea-90b5-f55d485aab45.gif)

**Expected behavior**
The new nodes are completely independent from the original ones.

**Comment by daviddq** [comment]
I have a clearer idea on what's happening. On copy/pasting nodes, the clones are being cloned on "copy" instead of on "paste". This way, if you "copy" one and "paste" many, nodes are cloned one time and then all "pastes" make reference to the same clone.

**Comment by blurymind** [comment]
Good catch! Feel free to submit the pr :)

**Comment by daviddq** [comment]
Submited PR #130

**Comment by blurymind** [comment]
merged now! Thank you for fixing it :)
