### ISSUE TITLE
Close the node editor when pressing ESC key

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#133]
I would like this feature. Does it make sense? Who or how decides which changes apply to the roadmap of the project.

**Comment by blurymind** [comment]
It does and wont be hard to implement. All keyup bindings are in app.js :)

**Comment by daviddq** [comment]
For now I focused on having ESC working, but yes, all input related code should be cleaned up.

**Comment by blurymind** [comment]
was windering wheter to introduce another class called input.js and move all the input code into it
