### ISSUE TITLE
Support for themes

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#134]
The current theme is OKish but I always like to customize my development environments. I would like to be able to select between a range of available themes. Also I would like to have a real "dark" theme, not an "invert" filter. Does it make sense?

**Comment by blurymind** [comment]
It does :) Can you mockup how themes will be changed? We currently dont have a preferences dialogue, but it would be quite nice to get it and expose some more yarn settings in it.

**Comment by blurymind** [comment]
Trello ticket added
https://trello.com/c/PFNrTBh9/14-add-support-for-theming
