### ISSUE TITLE
Node titles are case sensitive

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#135]
Nodes can have same title with different capitalization:

![image](https://user-images.githubusercontent.com/6022674/78367862-07e8ef00-75c3-11ea-8fad-4aba95c82d12.png)

I don't know if this is a bug or a feature.

**Comment by blurymind** [comment]
I think bondageJS supports it, so we are ok for now :) not sure if yarn spinner does.
It all depends on if the runtimes support it

**Comment by blurymind** [comment]
you can actually now playtest your node connections directly inside Yarn. Its using bondagejs. If varied casing of the same node crashes bondagejs or yarn spinner in unity, then we need to validate it

**Comment by daviddq** [comment]
While titles are allowed to mix upper/lower case letters some parts of the editor are treating them as case insensitive converting titles to trimmed lowercase to perform several actions. Some examples:

![Captura de pantalla 2020-04-14 a las 21 03 33](https://user-images.githubusercontent.com/6022674/79263870-e7a71300-7e93-11ea-918f-d45018613318.png)

![Captura de pantalla 2020-04-14 a las 21 04 25](https://user-images.githubusercontent.com/6022674/79263882-ed045d80-7e93-11ea-8d26-3fdaf6f0f322.png)

![Captura de pantalla 2020-04-14 a las 21 04 51](https://user-images.githubusercontent.com/6022674/79263894-f097e480-7e93-11ea-9f70-df3bca42ad3d.png)

This makes me think we should convert all titles to trimmed/lowercase on the data model on save.

**Comment by blurymind** [comment]
In the case of filtering out or searching, the conversion is to make them
easier to find. In the other two cases I am not sure why I did that and
made them lowercase, but it looks like a mistake now

**Comment by daviddq** [comment]
It's not clear to me whether this is an issue or not. I'm closing the issue. Reopen it when/if needed.
