### ISSUE TITLE
Version number inconsistencies

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#136]
**Current behavior**
When downloading Yarn Editor the installer name on Windows is Yarn.Editor.Setup.0.2.4.exe, but when running the editor it says 0.4.1. 

Also, after latest the 4 PR the version number is still 0.4.1

**Expected behavior**
a) Installer name reflects the real version number
b) Whenever changes are introduced on the project the appropriate version segment (major, minor or patch) should be updated.

**Comment by blurymind** [comment]
yes agreed :) pr welcome. Was actually wondering if we can set up some sort of an automatic electron auto building

**Comment by daviddq** [comment]
I'm setting up continuous integration in my fork and I see that electron build is trying to publish to the snap store. Is this something intentional or is it just the default electron's build process?

[image](https://user-images.githubusercontent.com/6022674/78504867-eda04400-776f-11ea-9548-930d5e47a353.png)

**Comment by blurymind** [comment]
I think it generates a snap package by default, which is kind of
convenient. I don't think it actually publishes it somewhere.

**Comment by daviddq** [comment]
I tries to but fails. To instruct it not to publish you need to add "--publish never".

I've got the linux version automatically building and publishing the artifact on GitHub. Are you interested in CI workflows? Do you want me to PR this feature?

**Comment by blurymind** [comment]
Yeah sure :) let's try it out. That way our users will get electron builds
more often too
