### ISSUE TITLE
Editor uses BBCode ([b] ... [/b]) to express rich text while Unity uses HTMLish (<b> ... </b>)

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#140]
Any chance to use HTMLish like unity does or being able to choose which one to use?

**Comment by desplesda** [comment]
HTML-ish would be preferred, because Yarn Spinner 1.1 uses [ and ] to delineate syntactic elements like format functions.

**Comment by blurymind** [comment]
would be nice if we have a way to switch between the two, since gdevelop uses bbcode atm

**Comment by daviddq** [comment]
Could you point to that Unity extension?

We could add that "Richtext format" setting to the new settings panel, together with the theme selection 😜

**Comment by blurymind** [comment]
Yes of course.It's made by @charblar 
https://github.com/radiatoryang/merino

I would welcome a pr that gives us a preference dialogue :) It would be best if we discuss via some mockup how it would be summoned and used? Perhaps via the file menu?

**Comment by blurymind** [comment]
Trello ticket added
https://trello.com/c/XehHOYJA/17-add-support-for-html-tags-enabled-in-preferences

**Comment by blurymind** [comment]
sent you an invite to join the board

**Comment by daviddq** [comment]
When changing the markup language in settings (i.e. from bbcode to html), shall we replace the markup of the currently existing bodies to match the new markup language? My guess is "yes" but I prefer to ask because it is a destructive operation.

**Comment by blurymind** [comment]
It would be nice if that is optional.. something like "convert document to bb/html" button in preferences

**Comment by daviddq** [comment]
@blurymind This feature is implemented in #181. Please, provide feedback when possible.

**Comment by blurymind** [comment]
Sorry I havent had a chance to look at it yet. Will do a review soon

**Comment by blurymind** [comment]
So I had a look at the PR and it mostly works. There are a few broken things for which I left comments/screenshots and an example file for you to test :)

**Comment by daviddq** [comment]
I fixed most of the problems you reported.

**Comment by blurymind** [comment]
Thank you for the fantastic work so far! The PRs not only add new features, but also reorganise the code very well :+1:
