### ISSUE TITLE
Create a "Settings" dialog where you can specify your personal preferences

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#143]
For now we could put there:

- Richtext format (BBCode or Unity HTMLish)
- Language (we can remove it from the node editor)
- Theme (dark/light or even a list of different themes)

![image](https://user-images.githubusercontent.com/6022674/78646550-7ecf0200-78b9-11ea-99fa-6eb4e6d6042e.png)

![image](https://user-images.githubusercontent.com/6022674/78648775-c6a35880-78bc-11ea-8d97-cbdfc3b12ad6.png)

**Comment by blurymind** [comment]
Yup, looks good to me :)  But I have some notes

I like that you added the language option there. It is actually one thing that I want moved out of the node editor. If you add the language option to the settings window, can you please take it out of the node editor?

Can we move the settings button inside the File menu? Most other software has it there and its not something I expect the user will be accessing very often, so I dont see a reason to designate precious space for it there.
I am also saying this because I plan to add some more stuff there in the future and the area is kind of running out  of space.

Another note: for the Rich text format option, can we call it XML/whatever it is instead of Unity? There are other game engines that use the format and Unity shouldnt be branding the Yarn editor, as we are made for all engines :)

**Comment by daviddq** [comment]
> ...can you please take it out of the node editor?

Sure that was the intent.

> Can we move the settings button inside the File menu?

Sure. Regarding this, I would do a whole rework of the UI. I love how Twinery does it, everything on a single bar: elegant, clean and intuitive.

![image](https://user-images.githubusercontent.com/6022674/78655449-500b5880-78c6-11ea-80d8-70bdb8d8f943.png)

I know this is very subjective, that's why I wanted themes, for everyone to be able to choose. Do you know any good UI/UX designer willing to collaborate? 😅 

> ...for the Rich text format option, can we call it XML/whatever...

Cool!

Yes, storing the settings was concerning me. Ideally I would store this settings per-project, but Yarn Edito has no "project" concept. So I think the way to go is to use window.localStorage on a per-browser approach.

Although a cool feature, this issue is _nice-to-have_ but not a _blocker_ for me, so I'll put it on hold.

**Comment by blurymind** [comment]
> Sure. Regarding this, I would do a whole rework of the UI. I love how Twinery does it, everything on a single bar: elegant, clean and intuitive.
> 
> ![image](https://user-images.githubusercontent.com/6022674/78655449-500b5880-78c6-11ea-80d8-70bdb8d8f943.png)
 
> I know this is very subjective, that's why I wanted themes, for everyone to be able to choose. Do you know any good UI/UX designer willing to collaborate? 
> 

That is a fantastic idea. We can have a Twine theme, but at the same time lets keep Yarn's default theme and layout as it is :)  Alot of people using it love it and wouldn't like us changing it into something drastically different. I do know a UIX designer. Do you need help with icons?

> Yes, storing the settings was concerning me. Ideally I would store this settings per-project, but Yarn Edito has no "project" concept. So I think the way to go is to use window.localStorage on a per-browser approach.
> 

Lets go with  window.localStorage :) 

It would also be nice if we can pass a settings object when we initiate Yarn from an app that is bundling it. One that sets the default initial settings for the user.
You can see how its bundled in Gdevelop for example
https://github.com/4ian/GDevelop/blob/master/newIDE/app/public/external/yarn/yarn-main.js

**Comment by daviddq** [comment]
Should this go to settings dialog?

![image](https://user-images.githubusercontent.com/6022674/79259522-25546d80-7e8d-11ea-8ca3-f048872d7df3.png)

**Comment by blurymind** [comment]
yeah I think so. All settings that must persist should go to settings

**Comment by blurymind** [comment]
trello ticket added
https://trello.com/c/sJuu5FI8/13-add-a-settings-dialog

**Comment by daviddq** [comment]
I just noticed there's a Trello board and I'm on it 😄 

Use my already existing Trello user if you want (daviddiaz3)

**Comment by blurymind** [comment]
ah ok, I will amend it :)

Btw feel free to add cards to the board. You are a good contributor to this project

**Comment by desplesda** [comment]
Seconded!!

**Comment by blurymind** [comment]
now that the settings dialog is merged, can we close this :)

**Comment by daviddq** [comment]
Sure thing 👍

**Comment by blurymind** [comment]
Thanks for implementing this :1st_place_medal:
