### ISSUE TITLE
This search boxes should be unified

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#152]
This search boxes should be unified removing the "open" item for simplicity and consistency:

![Captura de pantalla 2020-04-10 a las 11 55 06](https://user-images.githubusercontent.com/6022674/78982346-3c5c2e00-7b22-11ea-84ae-1235d673b6c7.png)

**Comment by blurymind** [comment]
They search in a different way. One shows you overview of nodes that fit the query,  the other centers them in view on hover and and lets you open them on click.

You could have it so searching triggers the open drop down with results in it. That would unify them and keep both behaviours

**Comment by daviddq** [comment]
I know they behave different, but having 2 different searches is strange and a little bit messy. It's a completely subjective appreciation.

> You could have it so searching in the left...

Yes, that's exactly what I was thinking about. Let's refine the idea and come up with a super nice and clean search functionality.

**Comment by blurymind** [comment]
![searchMenu](https://user-images.githubusercontent.com/6495061/79016668-7b60a280-7b67-11ea-993b-340931706b7a.png)
