### ISSUE TITLE
Browser Editor cannot open a yarn file type.

### ISSUE THREAD

**Issue by fakegood** [YarnSpinnerTool/YarnEditor#156]
<img width="1280" alt="Screenshot 2020-04-12 at 9 36 03 PM" src="https://user-images.githubusercontent.com/5751850/79132951-cedc2600-7ddd-11ea-878a-54f9c424dcb4.png">

Browser Editor cannot open a yarn file type.
MacOS version **can** open a yarn file type.

**Expected Behaviour:**
Browser Editor to work the same way as standalone (Electron) version.

**Comment by blurymind** [comment]
I believe that this was recently fixed by @daviddq , I just need to publish his fix to the web version

**Comment by blurymind** [comment]
published now. You should see it fixed in about half an hour:)
