### ISSUE TITLE
Story preview breaks when I use commands

### ISSUE THREAD

**Issue by daviddq** [YarnSpinnerTool/YarnEditor#157]
Whenever I insert a command in my scripts the story preview:

a) first time it's run it gets stuck at the command
b) next runs simply don't run at all

![command](https://user-images.githubusercontent.com/6022674/79436541-4e7e1680-7fd1-11ea-92cd-80930b0b76d3.gif)

**Comment by blurymind** [comment]
yup, will need to fix this soon :)

**Comment by blurymind** [comment]
fixed via https://github.com/YarnSpinnerTool/YarnEditor/commit/80998f47d7eb88bc044f7a34f12fe2ea26ac7112
