### ISSUE TITLE
New Compile version?

### ISSUE THREAD

**Issue by Flyingvette** [YarnSpinnerTool/YarnEditor#168]
Saw that autosave was implemented, but sadly I only have the last compiled version 2.4 for windows. (Of course, I didn't really check until after it would have proved useful, haha / cry). In older versions I had been manually overwriting the files with direct pulls from github. It doesn't look like that's possible anymore.

Appreciate all the work you do on this. It's my favorite dialogue / text editor and sees lots of use.

**Comment by blurymind** [comment]
@daviddq actually implemented automatic electron builds, however the script doing them is missing the step to publish the builds at https://github.com/YarnSpinnerTool/YarnEditor/releases

It would be great if we can update it so our users can get the latest electron builds from master

**Comment by daviddq** [comment]
@blurymind I just noticed that the automatic Windows electron build is rotten. Probably related to the themes and webpack (not sure).

**Comment by blurymind** [comment]
> @blurymind I just noticed that the automatic Windows electron build is rotten. Probably related to the themes and webpack (not sure).

Just an update on this, @daviddq fixed the rotten windows autobuild, but we still lack the step in the script to add the builds to the releases page

**Comment by daviddq** [comment]
Auto release is implemented on PR #177

**Comment by daviddq** [comment]
@blurymind Did you give auto release process a try?

**Comment by blurymind** [comment]
@Flyingvette there is a new electorn release
https://github.com/YarnSpinnerTool/YarnEditor/releases

please test and report issues

**Comment by Flyingvette** [comment]
Downloaded and installed. Works great, thank you @blurymind and @daviddq . This remains a very valuable tool that I use several times a week, if not every day.

The only issue I see vs the previous build I had is that when I open up a json file none of the connecting arrows between the text boxes appear until I enter at least one of the boxes. Then the arrows downstream of the entered box will refresh. This wasn't the case when using v0.2.4. I tried saving a json out of v0.4 and reopening, but the issue persisted. I don't see an outstanding issue for this and don't know if this is intended behavior or not.

**Comment by daviddq** [comment]
It is not the intended behavior and I can't even reproduce it on my environment. @blurymind Can you reproduce this problem?

**Comment by blurymind** [comment]
i think it probably has nothing to do with this issue. Can you reproduce the issue on the webapp version of yarn?

**Comment by Flyingvette** [comment]
I installed this directly over my previous version and also have not restarted my machine since install. I've found other problems too, but I agree they should be separate issues.

**Comment by daviddq** [comment]
I can reproduce the issue on the Electron build for Mac (first time I tried it was the webapp).

**Comment by Flyingvette** [comment]
I found an additional issue. Please see if you can recreate using the Electron build. I am using Yarn with dark mode, may or may not be a factor.

1 - create a new yarn, change the initial block name title to a number (for example, '3'), add some gibberish text, add a link by typing '[[ 45'
2 - Save this as a json
3 - open the json you just recreated
4 - right click to make a new node, add a link by typing '[[ 76'

At this point you should be unable to exit the node editor box by clicking outside of the node editor or through other means. I can send a test file if you are unable to replicate.

**Comment by daviddq** [comment]
> I found an additional issue. Please see if you can recreate using the Electron build. I am using Yarn with dark mode, may or may not be a factor.

@Flyingvette Recently I found and fixed a problem when loading files that may be related to this issue. If in a hurry, you can find the associated build here (https://github.com/YarnSpinnerTool/YarnEditor/actions/runs/117029521). Otherwise, stay tuned for the next Electron release. Thanks a lot for your feedback.

**Comment by blurymind** [comment]
good catch and thanks to @daviddq for fixing this. Please download the latest electron build and test again. Let us know if it persists
https://github.com/YarnSpinnerTool/YarnEditor/releases/tag/v0.4.22

**Comment by Flyingvette** [comment]
First off, thank you!!! The issue with not being able to exit nodes is fixed.

The connection arrows do not refresh upon opening an existing file, but do once a new node is created.

New issue:
1 - create a new yarn file
2 - Right click to create a node
3 - Click left button on open area in yarn and drag to select both nodes
4 - Click trash bin on one of the selected nodes

Delete dialogue should appear. None of the options can be selected except for the check mark at the bottom. However, with multiple nodes, it appears that you need to select one of the options in the delete dialogue first before clicking the checkmark. User ends up having to force close the program to proceed.

**Comment by daviddq** [comment]
> The connection arrows do not refresh upon opening an existing file, but do once a new node is created.

I can't reproduce this anymore on version 0.4.24:

![arrows](https://user-images.githubusercontent.com/6022674/83347743-64e4f500-a327-11ea-9dee-90eae12a16ad.gif)

What version and operative system are you using?

> New issue:

The "delete thing" is a known issue and is already scheduled for fix.

**Comment by Flyingvette** [comment]
Gotcha, thank you! Verified the link issue is solved on 4.23.

**Comment by daviddq** [comment]
I've reviewed all issues mentioned on this thread and I think everything should be fix on the latest version: https://github.com/YarnSpinnerTool/YarnEditor/releases/tag/v0.4.26

Can we close this issue?

**Comment by daviddq** [comment]
> @Flyingvette have you found any other electron breaking issues?

If so, please, close this ticket and create a new one with the corresponding description. Tanks a lot.

**Comment by Flyingvette** [comment]
Thank you so much for getting it all working again. Really, really appreciate everything you do here.
