### ISSUE TITLE
Linux .desktop file

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [YarnSpinnerTool/YarnEditor#182]
For those using Linux I created a .desktop file:

```
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=Yarn
Icon=/path/to/Yarn/package.nw/Yarn.png
Exec="/path/to/Yarn/nw"
Path=/path/to/Yarn/
```

I renamed the `nw` folder to `Yarn`. Don't forget to rename the path to your installation path.

**Comment by blurymind** [comment]
I dont think this desktop file will work, unless you edit the paths.
Yarn no longer uses nwjs, so /nw is probably no longer relevant.

**Comment by blurymind** [comment]
closing this, as I believe the electron build already does add a menu icon on linux desktops.

Get a copy at
https://github.com/YarnSpinnerTool/YarnEditor/releases
