### ISSUE TITLE
No icon at "Save as twee/twee2" in electron version

### ISSUE THREAD

**Issue by i1qwert** [YarnSpinnerTool/YarnEditor#184]
Expected to see Twee icon which can be found in project https://imgur.com/9feSxRB

**Comment by i1qwert** [comment]
or release version is kinda old, just tested electron version from this repo  and everything seems fine https://imgur.com/2DPB48S

**Comment by blurymind** [comment]
I think @daviddq fixed that ages ago :)
What version were you using before? The one from this repo is the official one

**Comment by blurymind** [comment]
oh wait, you are right, the release version is probably old. We need to wait for git to build it

**Comment by blurymind** [comment]
Can you try with https://github.com/YarnSpinnerTool/YarnEditor/releases/tag/v0.4.20

and if it no longer persists, close this issue

**Comment by i1qwert** [comment]
yeah, now it's fine, thx
