### ISSUE TITLE
Cannot create links to new nodes after importing file

### ISSUE THREAD

**Issue by nadescape** [YarnSpinnerTool/YarnEditor#187]
After importing a file (I tried both JSON and Twee2) you can no longer create a new node by adding a link to the body of an existing node. A node will be created, but it will be given the name Node# instead of the name in the link, and the widget to edit the existing node will refuse to close. Every attempt to close the widget will result in a new Node# being created. If you remove the link to the new node you will be able to close the edit widget. You can still create links to existing node, so creating a new node and then adding the link is a viable workaround.

**Comment by nadescape** [comment]
As best I can tell, this issue was introduced on 4/23.

**Comment by blurymind** [comment]
@daviddq can you have a look if one of the recent PRs broke this? :)

**Comment by blurymind** [comment]
Autocreating a new node is completely broken at the moment, the user will get stuck inside the node editor, while yarn keeps making new nodes with the wrong name :sob:

**Comment by daviddq** [comment]
I'm on it

**Comment by daviddq** [comment]
I pushed a fix. It seems to be a bug while disabling KnockOut rate limit extender.

Thanks a lot @nadescape for your accurate description of the issue.

**Comment by nadescape** [comment]
thanks for the quick fix! :)
