### ISSUE TITLE
Ctrl+S after "Save as Yarn" not working

### ISSUE THREAD

**Issue by i1qwert** [YarnSpinnerTool/YarnEditor#189]
Steps:
1. Open yarn editor
2. Type something in node
3. Menu -> Save as Yarn -> Save somewhere
4. Edit again
5. Hit Ctrl + S
6. Check yarn file and see that it hasn't changed

Expected: saving with Ctrl+S after saving as yarn

same happens after just _opening_ yarn file, editing it and trying to save with Ctrl+S

**Comment by blurymind** [comment]
possibly broken recently by the input refactoring :cry: 
@daviddq  can you look into this? Sorry I didn't catch the regression at the pr. These refactorings are big

**Comment by daviddq** [comment]
Ctrl+S opens the browser's "save file" dialog in the webapp and saves the HTML page.

**Comment by blurymind** [comment]
> Ctrl+S opens the browser's "save file" dialog in the webapp and saves the HTML page.
> 
> Currently the shortcut to save is Ctrl+Alt+S:
> 
> ![image](https://user-images.githubusercontent.com/6022674/83252712-06dfd280-a1ac-11ea-85b4-ef8d4ce03911.png)

can we make it ctrl+S again? Thats the standard in most software and it was ctrl+s before :)

**Comment by blurymind** [comment]
actually maybe both ctrl+s and ctrl+alt+s should save the file. No need to add checks if its in electron

**Comment by daviddq** [comment]
a) It was Ctrl+Alt+S back in 0.2.4, way before I started working on this project:

![Captura de pantalla 2020-05-29 a las 13 11 39](https://user-images.githubusercontent.com/6022674/83254088-735bd100-a1ae-11ea-9022-33a4eb2b7c8f.png)

b) Ctrl+S won't work on webapp since it's captured by the browser.

c) Ctrl+S is already being handled. I just tested in the Electron build and worked properly.

**Comment by daviddq** [comment]
I just tested on Electron-Windows 0.4.20 and none of the save shortcuts work (Ctrl+S, Ctrl+Alt+S, Ctrl+Shitf+S)

**Comment by blurymind** [comment]
interesting, does windows have a different way of detecting the ctrl key?  I have no access to a windows computer

**Comment by daviddq** [comment]
I don't think so. I need to find the way to debug in Electron. We already have an issue in Electron (arrows not drawing until a node is edited and saved #168) and I would like to tackle both.

**Comment by blurymind** [comment]
to be clear the intended design for ctrl+s is to write changes to the currently edited file. It needs to know the path to it, know its format and know to save the changes.

If there is no path (no file saved or opened yet), then it needs to offer to save it so somewhere

**Comment by blurymind** [comment]
btw electron's api has useful methods to register global shortcuts
https://www.electronjs.org/docs/tutorial/keyboard-shortcuts
but they are electron specific. I would prefer to keepas much as the code platform independent as possible :)

**Comment by blurymind** [comment]
Why not use electron's debugger? Run yarn on localhost then cd to electron's folder and run npm start. Electron version of yarn 
 in dev mode opens with the debugger.

**Comment by blurymind** [comment]
good catch and thanks to @daviddq for fixing this. Please download the latest electron build and test again. Let us know if it persists
https://github.com/YarnSpinnerTool/YarnEditor/releases/tag/v0.4.22

**Comment by i1qwert** [comment]
yep, now it kinda works great but still there is a little problem - when you save at fresh start with Ctrl + Alt + S , you later expect it to save it with the Ctrl + S _automatically_, but it keeps opening save dialog. 

BUT Ctrl + S works fine after you open yarn file
