### ISSUE TITLE
Feature: indicate that file was edited/saved

### ISSUE THREAD

**Issue by i1qwert** [YarnSpinnerTool/YarnEditor#192]
It'll be kinda cool if user would see that he did not save his changes by looking for example at window title which would say smth like:
`C:\Test.yarn [edited]`
or
`C:\Test.yarn *`

And after save:
`C:\Test.yarn`

**Comment by blurymind** [comment]
prefer the * approach. :)

**Comment by blurymind** [comment]
addded to trello here
https://trello.com/c/e82nSeta/38-add-to-window-title-when-the-file-has-been-edited

**Comment by blurymind** [comment]
I implemented this feature now
