### ISSUE TITLE
New files

### ISSUE THREAD

**Issue by pjarnfelt** [YarnSpinnerTool/YarnEditor#200]
When having an open document, then it is not possible to make a new file or get en empty project.

**Comment by blurymind** [comment]
You can open a new document however :)
Yes the "New" command is currently missing in the file menu. It shouldnt bee too hard to add, although that menu is getting a bit crowded now

**Comment by blurymind** [comment]
fixed via https://github.com/YarnSpinnerTool/YarnEditor/commit/912bb80d150f6ac7966f4a17a80c90932f287df0
