### ISSUE TITLE
Save as Yarn does not work.

### ISSUE THREAD

**Issue by elkontexo** [YarnSpinnerTool/YarnEditor#206]
Save as Yarn, does not open any Dialog. The Button flashes as if being clicked but nothing happens.
Tested in Desktop-Version, Firefox and Chrome Canary.

**Comment by blurymind** [comment]
I will fix this ASAP

**Comment by blurymind** [comment]
There is a pr for this atm that will likely fix it. I will try to get it in tomorrow

**Comment by blurymind** [comment]
@nospoone fixed it via https://github.com/YarnSpinnerTool/YarnEditor/pull/205

**Comment by elkontexo** [comment]
Thank you so much for the quick fix! It works like a charme again. Thank you for providing and maintaining this amazing tool.
