### ISSUE TITLE
Ios Support

### ISSUE THREAD

**Issue by mlflabs** [YarnSpinnerTool/YarnEditor#207]
Hello, first thx for a great app, i love this editor

Just wondering, if ios app is in works? 

If no one is doing it, i can try to make it, if i do and release to app store, is there anything i should consider (fully free, and opensource app besides this what else to consider)

Mike

**Comment by blurymind** [comment]
Should work on ios as a pwa. I don't have an iPhone to test it though

**Comment by mlflabs** [comment]
I was playing with it on ipad for a while, its really good, thx for the reply
