### ISSUE TITLE
"[[" tags will autocomplete even when autocompletion is disabled

### ISSUE THREAD

**Issue by twdziki** [YarnSpinnerTool/YarnEditor#210]
As mentioned in the summary, "]]" will be added regardless of whether Complete Tags is enabled or not.

**Comment by StefanJanssen95** [comment]
A quick check showed me this is the case for multiple (but not all) characters that open and close sections.
Characters it does happen with:
```
[
(
"
'
```
while it does happen with:
```
{
<
```
The autocompletion already happens with a single tag and I think this is a thing within Ace editor. I will check if this is an issue that we can solve here or if it's something we have to mention to the Ace team.

**Comment by StefanJanssen95** [comment]
I've just done some testing and it's an option in the Ace editor. I'm now implementing this as a new setting. Since I do see the "Complete Tags" setting as something different.
