### ISSUE TITLE
The node title seems to accept values which are not permitted

### ISSUE THREAD

**Issue by StefanJanssen95** [YarnSpinnerTool/YarnEditor#215]
About a year ago I read the YarnSpinner documentation and today I'm looking for projects I can contribute to (hacktoberfest). I just downloaded the editor while having a vague idea about the syntax and I noticed the Editor doesn't seem to validate the input of the Node title. 

I've created a single node with as name "1st line" which was permitted in the editor but threw an error in Unity. This name contains a space so is invalid. 
> The name of the node, in this case nodename, needs to be unique across the entire project, and can be any combination of upper or lower case letters and numbers. Node titles can’t have spaces.

**Comment by StefanJanssen95** [comment]
I'll pick this issue up myself. If someone could assign me that would be great :D

**Comment by desplesda** [comment]
Sure thing!
