### ISSUE TITLE
Node deselection behaviour

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#22]
<a href="https://github.com/desplesda"><img src="https://avatars1.githubusercontent.com/u/901768?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [desplesda](https://github.com/desplesda)**
_Thursday Feb 18, 2016 at 10:43 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/22_

----

- Clicking on a node once should select it, and deselect any other nodes.
- Clicking on the background should deselect all nodes.

(Currently, if you drag a box around nodes, the only way to **de**select them is to drag another box, and select either different nodes or no nodes. There's no other way to deselect nodes, I think?)

**Comment by desplesda** [comment]
<a href="https://github.com/InfiniteAmmoInc"><img src="https://avatars2.githubusercontent.com/u/6853794?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [InfiniteAmmoInc](https://github.com/InfiniteAmmoInc)**
_Friday Feb 19, 2016 at 05:34 GMT_

----

Got the second one working.

**Comment by desplesda** [comment]
<a href="https://github.com/InfiniteAmmoInc"><img src="https://avatars2.githubusercontent.com/u/6853794?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [InfiniteAmmoInc](https://github.com/InfiniteAmmoInc)**
_Friday Feb 19, 2016 at 05:38 GMT_

----

...and first one. There's a bug where the node highlights stop appearing if they've ever been marquee selected. Not sure what's up with that yet. :)

**Comment by desplesda** [comment]
<a href="https://github.com/desplesda"><img src="https://avatars1.githubusercontent.com/u/901768?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [desplesda](https://github.com/desplesda)**
_Friday Feb 19, 2016 at 07:54 GMT_

----

Verified that the first item (clicking a node deselects other nodes) works in the app, but not the second (clicking the background deselects all nodes). Here's a gif of what I'm seeing:

![yarn deselection](https://cloud.githubusercontent.com/assets/901768/13169514/3dbdf02a-d73a-11e5-9238-053b83ff88d5.gif)

**Comment by desplesda** [comment]
<a href="https://github.com/InfiniteAmmoInc"><img src="https://avatars2.githubusercontent.com/u/6853794?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [InfiniteAmmoInc](https://github.com/InfiniteAmmoInc)**
_Friday Feb 19, 2016 at 12:06 GMT_

----

Pushed a fix. The highlighting stuff I mentioned is still broken tho.

**Comment by desplesda** [comment]
<a href="https://github.com/InfiniteAmmoInc"><img src="https://avatars2.githubusercontent.com/u/6853794?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [InfiniteAmmoInc](https://github.com/InfiniteAmmoInc)**
_Friday Feb 19, 2016 at 12:17 GMT_

----

ugh, caused another bug tho. :P my html5/js game is weak

**Comment by FaultyFunctions** [comment]
Selection/deselection behavior has been fully implemented at this point. Although the current behavior is slightly different from the original discussion. Clicking on a single node will not select it and deselect all other nodes. However clicking on the background once will deselect all nodes. Additionally multiple nodes can also be selected or unselected by holding Ctrl + single clicking on nodes.

I don't believe the single click on a node should deselect all, however we can open this discussion back up if needed! I'm closing it for now since it's pretty old.
