### ISSUE TITLE
[Web] Inline expressions not working in playtesting

### ISSUE THREAD

**Issue by ChaosPhill** [YarnSpinnerTool/YarnEditor#220]
The inline expressions don't convert when playtesting them inside the YarnEditor.

Example:
What I write:
`<<set $potato to 5>>`
`I have {$potato} potatoes`
Want I want:
`I have 5 potatoes`
What I get in playtesting preview:
`I have {$potato} potatoes`

Using the web version of YarnEditor (version 0.4.102).

Not sure if I'm using the incorrect syntax, but I'm doing what's inside the Syntax Reference. I'm using a college computer so can't test on executable.

**Comment by blurymind** [comment]
This is a missing feature in bondagejs - there is a ticket opened for it already
https://github.com/hylyh/bondage.js/issues/59

**Comment by blurymind** [comment]
closing this, since the  request is really for a different project. Yarn editor itself doesnt handle any of the playtest parsing - it uses bondagejs

**Comment by ChaosPhill** [comment]
Ah okidokes, thank you!
