### ISSUE TITLE
Arguments passed to YarnEditor should be opened for editing in new window(s)

### ISSUE THREAD

**Issue by fmoo** [YarnSpinnerTool/YarnEditor#229]
If you make it so that positional arguments to the YarnEditor will automatically open the file for editing, then it's super easy to configure your OS so double clicking a .yarn file in Unity or in your file manager launches the editor, which can make working with lots of files a lot easier.

Currently positional arguments are ignored, so you have to manually launch the editor, before trying to find and open them through its file menu, etc.

**Comment by blurymind** [comment]
shouldnt be too hard to implement. Pr is welcome :)
