### ISSUE TITLE
Bug where if you load a node from another node in play mode and then click the title of the current node, it'll send you the editor of the loaded node over and over.

### ISSUE THREAD

**Issue by FaultyFunctions** [YarnSpinnerTool/YarnEditor#230]
Steps to reproduce:

1. Create two nodes.
2. Add a link to the second node from the first node.
3. Click play.
4. When the second node is loaded, click the title in the editor to enter "preview" mode in the first node.
5. Observe that it sends you to the second node's editor.
6. Also observe that this now happens on any node thereafter when you enter preview mode on any nodes.

I'm not really sure how to fix this. I think it's an error in `togglePlayMode` function when it's being called from `togglePreviewMode` in app.js.

**Comment by blurymind** [comment]
Its supposed to send you to the node that is playing when you exit play
mode

**Comment by FaultyFunctions** [comment]
Right but I guess the bug part is if you exit the second node's editor, and go back to the first node's editor it still sends you back to the second node.
![ezgif-5-36f68ba9beb1](https://user-images.githubusercontent.com/6508045/101280269-c7fb8c80-378d-11eb-92f2-288524000886.gif)

**Comment by blurymind** [comment]
Oh interesting 🤔 that does look like a bug
