### ISSUE TITLE
Rename linked nodes in existing links?

### ISSUE THREAD

**Issue by s1-en** [YarnSpinnerTool/YarnEditor#248]
On Twine, when I rename a node, it doesn't break already existing links but instead updates the links in the other nodes to reflect the changed identifier. Could this be implemented to Yarn Editor too?

**Comment by FaultyFunctions** [comment]
This is currently functional but for some reason it's only coded to work with `[[<optional choice text here>|nodeName]]` syntax, not with just `[[nodeName]]`. So you need the `|` before the node name, then it will work.

This should be updated, thanks for bringing this up!

**Comment by blurymind** [comment]
I think @daviddq originally implemented it. Maybe he could have a stab at this when he has some time?  :)

**Comment by daviddq** [comment]
Hey! I remember coding this back in the day... and it kind of worked. Maybe there was some regression?

I'm completely disconnected with the process of this project, but I will try and download the latest code and make some tests. I promise nothing.

**Comment by daviddq** [comment]
I prepared a quick PR to fix this: https://github.com/YarnSpinnerTool/YarnEditor/pull/274

**Comment by blurymind** [comment]
Thank you @daviddq 
Merged now :tada:
