### ISSUE TITLE
Release notes / version history

### ISSUE THREAD

**Issue by Firemaw** [YarnSpinnerTool/YarnEditor#254]
Possible to get a running release notes / version history going for new releases of the app? I can't see one anywhere. Let me know if there already is one. So that when users update to a new version they know what has changed.

**Comment by blurymind** [comment]
The only way to see them right now is via the commits where you download the release.
![image](https://user-images.githubusercontent.com/6495061/125195411-62a0da00-e24d-11eb-878b-a600330455a5.png)
There are no plans to add this to yarn's interface, so I will close this ticket for now.

A pr would be welcome of course
