### ISSUE TITLE
Create new nodes from links when closing a node?

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#27]
<a href="https://github.com/cjacobwade"><img src="https://avatars0.githubusercontent.com/u/4643180?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cjacobwade](https://github.com/cjacobwade)**
_Friday Mar 25, 2016 at 05:43 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/27_

----

Would be nice to auto create nodes after adding a link to a non-existent node.

**Comment by desplesda** [comment]
<a href="https://github.com/desplesda"><img src="https://avatars1.githubusercontent.com/u/901768?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [desplesda](https://github.com/desplesda)**
_Saturday Mar 26, 2016 at 17:04 GMT_

----

The alternative would be to display some kind of warning that a node is linking to nodes that don't exist.

**Comment by desplesda** [comment]
<a href="https://github.com/com1clyf3"><img src="https://avatars1.githubusercontent.com/u/6562812?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [com1clyf3](https://github.com/com1clyf3)**
_Tuesday Jun 19, 2018 at 17:42 GMT_

----

I'm with @cjacobwade . This feature really enables quick branch design in Twine, and I expected it in Yarn.

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Wednesday Jun 27, 2018 at 15:26 GMT_

----

I added this to the electron port today. Will do a merge tonight :) 
![yarn-autonewnodefromchoice](https://user-images.githubusercontent.com/6495061/41983609-8f78d286-7a26-11e8-916b-d6272d184843.gif)

Here is the pull request
https://github.com/InfiniteAmmoInc/Yarn/pull/68

**Comment by blurymind** [comment]
this can technically be closed now, since the electron branch is the main one :)
