### ISSUE TITLE
"Play" mode?

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#29]
<a href="https://github.com/HawkenKing"><img src="https://avatars0.githubusercontent.com/u/5999766?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HawkenKing](https://github.com/HawkenKing)**
_Monday Mar 28, 2016 at 06:13 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/29_

----

Would be nice if there were a super simple way to just check out your stories like in Twine. (unless there already is?!)

**Comment by desplesda** [comment]
<a href="https://github.com/catherineomega"><img src="https://avatars1.githubusercontent.com/u/1645832?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [catherineomega](https://github.com/catherineomega)**
_Sunday Oct 15, 2017 at 20:00 GMT_

----

Robert Yang made an excellent tool for just this purpose: https://github.com/radiatoryang/Yarn-Weaver

Someone should add it to the docs! :)

**Comment by desplesda** [comment]
<a href="https://github.com/desplesda"><img src="https://avatars1.githubusercontent.com/u/901768?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [desplesda](https://github.com/desplesda)**
_Monday Oct 16, 2017 at 01:24 GMT_

----

Agreed! Send in a pull request and I'll merge it!

**Comment by desplesda** [comment]
<a href="https://github.com/charblar"><img src="https://avatars0.githubusercontent.com/u/25385583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [charblar](https://github.com/charblar)**
_Tuesday Jun 12, 2018 at 14:36 GMT_

----

Being implemented via [bondage.js](https://github.com/jhayley/bondage.js) in https://github.com/InfiniteAmmoInc/Yarn/issues/29.

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Friday Jun 22, 2018 at 08:37 GMT_

----

It's available in the electron port
https://github.com/InfiniteAmmoInc/Yarn/pull/68

Download it from here
https://github.com/blurymind/Yarn/releases/tag/untagged-1933231011a749959b56

**Comment by desplesda** [comment]
<a href="https://github.com/fragmental"><img src="https://avatars1.githubusercontent.com/u/5062896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fragmental](https://github.com/fragmental)**
_Monday Sep 24, 2018 at 17:36 GMT_

----

@blurymind your link is dead

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Monday Sep 24, 2018 at 17:47 GMT_

----

@fragmental its here
https://github.com/InfiniteAmmoInc/Yarn/tree/electron
Unfortunately @charblar hasn't made it the main branch, so there are no builds of it

**Comment by desplesda** [comment]
<a href="https://github.com/fragmental"><img src="https://avatars1.githubusercontent.com/u/5062896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fragmental](https://github.com/fragmental)**
_Monday Sep 24, 2018 at 17:53 GMT_

----

@blurymind thanks.  I was looking for a windows build.  The win64 build link is dead, on the readme.

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Saturday Nov 24, 2018 at 10:59 GMT_

----

I updated the links in my pull here:
#80 
:)
I fixed some of the bugs you reported in it too

Download here
https://github.com/blurymind/Yarn/releases/edit/v0.3.2

**Comment by blurymind** [comment]
The play mode is there, but needs refactoring to be exposed to the UI again. Once done I will be able to close this

**Comment by FaultyFunctions** [comment]
This has been implemented. Closing for now since it's been inactive.
