### ISSUE TITLE
drag file in to Yarn makes yarn die

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#32]
<a href="https://github.com/HawkenKing"><img src="https://avatars0.githubusercontent.com/u/5999766?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HawkenKing](https://github.com/HawkenKing)**
_Monday Mar 28, 2016 at 08:56 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/32_

----

If I drag a Json file into the main window of yarn, would be nice if it opened the file, currently it just shows the raw Json

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Friday Jun 22, 2018 at 08:35 GMT_

----

Like this? =)
![yarn-dropfile](https://user-images.githubusercontent.com/6495061/41766680-8ce4ad2c-75ff-11e8-950e-f35346769c97.gif)

dropping multiple files appends them:
![yarn-dropfilesmany](https://user-images.githubusercontent.com/6495061/41774372-6978e9da-7617-11e8-8860-3f0189abd4aa.gif)

Comit coming later today in the electron port
#68

**Comment by blurymind** [comment]
Again, this can be closed :)
