### ISSUE TITLE
auto complete node names

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#34]
<a href="https://github.com/HawkenKing"><img src="https://avatars0.githubusercontent.com/u/5999766?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HawkenKing](https://github.com/HawkenKing)**
_Monday Mar 28, 2016 at 09:10 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/34_

----

would be nice if when typing [[ click here | NODENAME ]] that NODENAME would suggest-complete if NODENAME exists, or error underline if it didn't. Similar to using a code editor.

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Thursday Jun 21, 2018 at 18:19 GMT_

----

like this?
![yarn-linkmaking](https://user-images.githubusercontent.com/6495061/41685764-7bf48d1a-74d9-11e8-89bc-b7bae39470f6.gif)
It's available in the electron port
#68

**Comment by blurymind** [comment]
This is implemented already and the bug can be closed
