### ISSUE TITLE
Having Trouble Saving Anything

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#44]
<a href="https://github.com/RyokiRayn"><img src="https://avatars2.githubusercontent.com/u/25807987?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [RyokiRayn](https://github.com/RyokiRayn)**
_Thursday Feb 16, 2017 at 01:35 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/44_

----

So if I open Yarn in either NW.js or my browser, I can write out the dialogue tree I'm working on just fine, but whenever I go to save I get the four file type options but none of them save anything. In NW.js, if I click save as _____ it opens a separate window with a word document of my tree in it and will not save the file type I request.

**Comment by desplesda** [comment]
<a href="https://github.com/jettraverso"><img src="https://avatars0.githubusercontent.com/u/25624042?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jettraverso](https://github.com/jettraverso)**
_Wednesday Aug 02, 2017 at 16:34 GMT_

----

My friend and I are using the browser editor, and we cannot save either. Is this a bug from a recent release?

**Comment by desplesda** [comment]
<a href="https://github.com/Klash120"><img src="https://avatars2.githubusercontent.com/u/30874540?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Klash120](https://github.com/Klash120)**
_Wednesday Aug 09, 2017 at 17:39 GMT_

----

Ditto. Using Chrome. Disabling any Adblocker seems to allow saving. Though, nothing will load now :x

**Comment by desplesda** [comment]
<a href="https://github.com/charblar"><img src="https://avatars0.githubusercontent.com/u/25385583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [charblar](https://github.com/charblar)**
_Wednesday Jun 13, 2018 at 02:32 GMT_

----

Confirmed, unable to reproduce workaround mentioned by @Klash120. Will readdress after finishing electron port.

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Monday Aug 13, 2018 at 07:40 GMT_

----

@RyokiRayn does that also happen in the electron version?

**Comment by blurymind** [comment]
can you confirm if this bug still persists?

**Comment by daviddq** [comment]
What's the current state of this issue? Can we close it?

**Comment by blurymind** [comment]
This bug is quite ancient and the guy who reported it hasnt responded for a year. I think its safe to close it. Someone will reopen the issue if it happens again
