### ISSUE TITLE
Multiple yarn instances not possible

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#59]
<a href="https://github.com/LiamSauve"><img src="https://avatars2.githubusercontent.com/u/2172885?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LiamSauve](https://github.com/LiamSauve)**
_Thursday Oct 26, 2017 at 20:33 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/59_

----

would be nice if you could open multiple yarn instances (at least on Windows, not sure about other platforms)

**Comment by desplesda** [comment]
<a href="https://github.com/charblar"><img src="https://avatars0.githubusercontent.com/u/25385583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [charblar](https://github.com/charblar)**
_Wednesday Jun 13, 2018 at 02:27 GMT_

----

Confirmed on my end, will revisit after finishing port to electron to see if this is still an issue.

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Thursday Jun 21, 2018 at 15:19 GMT_

----

@charblar This is a non-issue in the electron port :) 
![yarnelectron](https://user-images.githubusercontent.com/6495061/41728489-d7138d96-756e-11e8-8e7b-9687a7768221.PNG)

@LiamSauve 
It's available in the electron port
#68

Download it from here
https://github.com/InfiniteAmmoInc/Yarn/pull/80

**Comment by blurymind** [comment]
Now that the electron branch is the main one, I think we can close this bug. I don't seem to have the ability to close bugs any more though :)
