### ISSUE TITLE
Idea: Bundle yarn with gdevelop - a great open source game engine 

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#67]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [blurymind](https://github.com/blurymind)**
_Saturday Jun 02, 2018 at 21:24 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/67_

----

Gdevelop is an incredibly fun and user friendly open source game engine that allows even people with no programming knowledge to create games.
https://gdevelop-app.com/
For programming it uses event sheets - similar to the ones in construct2 and clickteam fusion.
![events 88952ff1](https://user-images.githubusercontent.com/6495061/40881039-af294168-66b4-11e8-888c-e186ff390af5.png)

Now the reason for this proposal is gdevelop's new editor. I have been making some contributions to it lately and learning it's design - because it is written in javascript, using electron.

The editor is very user friendly, but it lacks storytelling tools - one has to make a story system in  it from scratch (even with event sheets).

Since both Yarn is web based and gdevelop's new editor is web based- I can try bundling yarn in it. But to do it, Yarn needs to be ported over to electron.
I already ported yarn to electron for a personal project myself- and got it to communicate with my app- so that is out of the way. I had to however change some of the code and add code to get it to work and open and save files like before.

I am thinking of using the excellent bondage.js for the story parsing part
https://www.npmjs.com/package/bondage
Many thanks to @jhayley for implementing it!

Posting here to see if there is community interested in this :)

Would you guys be interested to use yarn in an engine that is much smaller and easier to use than Unity3d? An engine that is both open source and actually would come packaged with yarn editor built into it? 
:)
related issue post: https://github.com/4ian/GD/issues/511

**Comment by desplesda** [comment]
<a href="https://github.com/charblar"><img src="https://avatars0.githubusercontent.com/u/25385583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [charblar](https://github.com/charblar)**
_Wednesday Jun 13, 2018 at 02:29 GMT_

----

Sounds interesting, I believe this would be a question for @AlecHolowka to give his final say on.

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Wednesday Jun 13, 2018 at 08:46 GMT_

----

yes of course, also up to @4ian - Florian Rival - the creator of gdevelop.

I just personally feel that the two projects compliment each other on many levels - much more than yarn and Unity do.
Both Yarn and gdevelop are built on top of the same technology, they are both open source and target the same type of creative people- young story tellers/designers.

Because of the license, you can literaly bundle the two together and have them closely interact in ways that would be impossible with Unity.

The more I learn about how the two work, the more I see the potential of a collaboration of these two communities :)

Yarn and Gdevelop can be stronger together, because they have alot in common. They even look similar in terms of design. Wouldnt it be nice to be able to use yarn in a game engine out of the box- without having to rely on third party api/plugins. Have it open straight inside the game engine's editor, and the game engine be ready to use its data - exposing it in a very user friendly way.

That said yes- yarn will of course remain a tool that can be used with any other game engine. Because its open source - I think it could be used more in other open source projects if it was distributed as an npm package for example :) 

My goal here really is to try and test the waters- see what other people think. Will the yarn users be interested in doing some game jams with gdevelop - knowing that it literaly comes with yarn built into it? Will they create games with gdevelop - knowing that it will let them make a story based 2d game quicker without even knowing a programming language - like Unity's C#?

In terms of actually making it happen - I already know enough about the two to put yarn editor inside gdevelop's newide and interact with it. The crust of the work would be in implementing a game behavior in gdevelop's js engine to expose the yarn story data to the event sheet. 
https://github.com/4ian/GDevelop.js

The story tree parsing is largely solved already by bondage.js - which I have already integrated in yarn's electron port to use for testing a story tree

**Comment by blurymind** [comment]
This is getting close to being closed now. There is a PR at gdevelop bundling yarn

**Comment by blurymind** [comment]
yarn is a part of GD now, so closing this now
