### ISSUE TITLE
Resizing window to narrow profile offsets connection lines

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#77]
<a href="https://github.com/b-erv"><img src="https://avatars0.githubusercontent.com/u/17258819?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [b-erv](https://github.com/b-erv)**
_Thursday Aug 09, 2018 at 18:36 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/77_

----

When the Yarn window is close to or at its minimum width, any lines between nodes get shunted to one side and no longer line up. Happening for me consistently at various resolutions and display magnification settings.
![resize](https://user-images.githubusercontent.com/17258819/43918439-15efe6d4-9be1-11e8-9d2a-435489c3c8b5.gif)

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Thursday Aug 09, 2018 at 20:26 GMT_

----

Does that also happen in the electron version?

Also can you please zip the file you have open and attach it to your post
here

**Comment by desplesda** [comment]
<a href="https://github.com/b-erv"><img src="https://avatars0.githubusercontent.com/u/17258819?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [b-erv](https://github.com/b-erv)**
_Friday Aug 10, 2018 at 21:35 GMT_

----

Yes, the same behaviour is occurring for me across versions. Additionally, it happens the same way with all .yarn files, even newly-created ones. Such as here:
[demo.yarn.txt](https://github.com/InfiniteAmmoInc/Yarn/files/2279529/demo.yarn.txt)

**Comment by desplesda** [comment]
<a href="https://github.com/julsam"><img src="https://avatars3.githubusercontent.com/u/340056?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [julsam](https://github.com/julsam)**
_Saturday Aug 11, 2018 at 06:37 GMT_

----

I've been able to reproduce the issue with the NWjs build (aka master) but not with the electron build.

Maybe it has to do with this? Not sure.
```css
/* --- MEDIA --- */

@media (max-width: 830px) {
	.app-search {
		position: relative;
		float: left;
	}
	.app-menu {
		position: relative;
		float: right;
		margin-top: 20px;
	}
}
```

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Saturday Aug 11, 2018 at 09:49 GMT_

----

for the electron build - if it aint broke - no need to fix it :) might cause some regression

**Comment by desplesda** [comment]
<a href="https://github.com/julsam"><img src="https://avatars3.githubusercontent.com/u/340056?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [julsam](https://github.com/julsam)**
_Saturday Aug 11, 2018 at 09:59 GMT_

----

@blurymind you misunderstood me :wink: 
I was pointing out that the issue could be related to this css rule in the __master branch__, not the electron one :stuck_out_tongue: 


This css rule will move the right menu buttons when the window's width is lower than 830px, which is when the issue with the arrows seems to be happening.
But I've only been working in the electron branch so far, so I'm not sure what's really happening, I'll let others investigate.

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Monday Aug 13, 2018 at 07:38 GMT_

----

@julsam do we patch it in the nwjs version? I want to focus on maintaining the electron one

**Comment by desplesda** [comment]
<a href="https://github.com/julsam"><img src="https://avatars3.githubusercontent.com/u/340056?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [julsam](https://github.com/julsam)**
_Saturday Aug 25, 2018 at 12:21 GMT_

----

@blurymind it's not a major bug, so i'm not sure patching the nwjs is worth it since the plan is to go full electron in the long term. There's a lot more important issues to fix in the nwjs version anyway (but i'm more focused on the electron branch myself).

**Comment by blurymind** [comment]
is this bug still here? I cant seem to reproduce it

**Comment by FaultyFunctions** [comment]
This seems to be fixed and has been inactive for a while. I'm closing the issue but feel free to re-open if need be!
