### ISSUE TITLE
Zoom only works on connections, not nodes

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#81]
<a href="https://github.com/ViniciusMeirelles"><img src="https://avatars1.githubusercontent.com/u/29467256?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ViniciusMeirelles](https://github.com/ViniciusMeirelles)**
_Monday Sep 03, 2018 at 22:05 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/81_

----

As the title says, when I use the mouse scroll wheel to zoom out of a file, only the connections get smaller. The nodes have fixed size.

**Comment by desplesda** [comment]
<a href="https://github.com/julsam"><img src="https://avatars3.githubusercontent.com/u/340056?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [julsam](https://github.com/julsam)**
_Wednesday Sep 26, 2018 at 14:48 GMT_

----

Hi, does it happen every time? What version are you using / what OS?
It happened to me a couple times, only on MacOS with the electron branch. But i can't find a way to reproduce it, and I have no idea why it's happening...

**Comment by desplesda** [comment]
<a href="https://github.com/NamelessPerson"><img src="https://avatars3.githubusercontent.com/u/1820878?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NamelessPerson](https://github.com/NamelessPerson)**
_Saturday Jan 26, 2019 at 04:04 GMT_

----

I have this problem often as well on Windows. I might suggest moving to graphics library like pixi to render the node graph. Currently am playing around with that

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Saturday Jan 26, 2019 at 10:33 GMT_

----

@NamelessPerson pull requests for that are welcome :) 👍

**Comment by daviddq** [comment]
Node graph went through an intense refactoring during the past months. Is this still happening on any scenario on the latest builds? If no, please close the issue. Thanks.

**Comment by FaultyFunctions** [comment]
This seems to be fixed and have been inactive for a while. I'm closing the issue but feel free to re-open if need be!
