### ISSUE TITLE
When exporting as JSON, if you rename the file from 'file' it will incorrectly save the file.  If you create the file as 'file' then rename it, the file will work correctly

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#82]
<a href="https://github.com/hadarawhite"><img src="https://avatars3.githubusercontent.com/u/17689787?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hadarawhite](https://github.com/hadarawhite)**
_Tuesday Sep 11, 2018 at 19:23 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/82_

----

If I am exporting as a JSON the file will have the name 'file' by default.  If I save with this it will export correctly but if I name it to anything else, the file will not work.  If you export it as 'file' then renamed the file it will work correctly.

EDIT: Accidentally posted with out finishing the title/description

**Comment by blurymind** [comment]
@hadarawhite does this bug still occur? The save functionality has gone through many changes and this bug is awfully old.

**Comment by FaultyFunctions** [comment]
I believe this has been fixed for a while now. I'm closing since this is inactive but feel free to re-open in case I missed anything!
