### ISSUE TITLE
Feature Request: Unsaved Files Give Warning When Opening New Yarn Files

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#94]
<a href="https://github.com/tomdominer"><img src="https://avatars2.githubusercontent.com/u/8956351?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomdominer](https://github.com/tomdominer)**
_Wednesday Feb 06, 2019 at 15:06 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/94_

----

I've lost a fair bit of work but forgetting to manually save my yarn file and moving to work on another. It would be great if the editor warned you of unsaved changes when you select to open a new file.

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Wednesday Feb 06, 2019 at 15:34 GMT_

----

that is actually fairly easy to implement. I will pick it up if nobody is interested :)

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Wednesday Feb 06, 2019 at 19:10 GMT_

----

implemented via https://github.com/InfiniteAmmoInc/Yarn/commit/dbf94c97c02e29524f6d7d6fc0240d29970420f9
:) 
please try from git

**Comment by desplesda** [comment]
<a href="https://github.com/Flyingvette"><img src="https://avatars0.githubusercontent.com/u/8788482?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Flyingvette](https://github.com/Flyingvette)**
_Wednesday Feb 06, 2019 at 19:31 GMT_

----

If we don't have an autosave feature yet, it might be a good time to stick one in. Even just a single Autosave.json to the root directory every 15 minutes could be a lifesaver for someone.

You've been working really hard at this @blurymind. It's very appreciated :)

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Wednesday Feb 06, 2019 at 19:47 GMT_

----

@Flyingvette can you open a new issue about it please :) It would help me with closing this one.
Will look into it. It shouldnt be too hard to add either.

Lets discus how it will work there

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Friday Feb 08, 2019 at 19:11 GMT_

----

@Flyingvette this is now in the latest electron version - you can enable automatic file saving by editing a json settings file that yarn editor creates when you close it.
https://github.com/InfiniteAmmoInc/Yarn/commit/c54dd56ad9df2e9702d5db95dbe081030cc315dd

open yarn-electron and close it. Then edit
`C:\Users\YOU\.yarn-story-editor.json`
```
settings:{
      autoSave:-1
    }
```

to be 
```
settings:{
      autoSave:5
    }
```
5 will make it auto save every 5 minutes

Later on I plan to expose these settings to a config gui

**Comment by blurymind** [comment]
this may need a  new settings dialogue window to expose to the ui

**Comment by FaultyFunctions** [comment]
As far as I'm aware this has been fully implemented. Closing for now, but feel free to re-open if there is something I missed!
