### ISSUE TITLE
About night in the woods localization

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#95]
<a href="https://github.com/zellfy"><img src="https://avatars3.githubusercontent.com/u/45615697?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zellfy](https://github.com/zellfy)**
_Monday Mar 04, 2019 at 04:53 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/95_

----

Thank you for your working.
I just want to know if yarn can edite the dialogue from English to another type of lanuage, just like chinese.
Because I know that Night in the woods used spritefont of unity, I have to make a bitmap or something.
So can I use yarn to do it?
Thank you for reading.

**Comment by desplesda** [comment]
<a href="https://github.com/evanmalmud"><img src="https://avatars2.githubusercontent.com/u/2916032?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [evanmalmud](https://github.com/evanmalmud)**
_Monday Jul 22, 2019 at 16:23 GMT_

----

I figure you most likely edit your flow with the Chinese in. And then your that yarn export in unity. 
I might be wrong, just started using this.

**Comment by FaultyFunctions** [comment]
Closing this since it's been inactive for a while now, but for future reference in case anyone stumbled upon this. Check https://yarnspinner.dev/docs/unity/localisation/ for more information about one possible solution.
