### ISSUE TITLE
web hosted yarn instance

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnEditor#96]
<a href="https://github.com/arnemileswinter"><img src="https://avatars1.githubusercontent.com/u/45700009?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arnemileswinter](https://github.com/arnemileswinter)**
_Friday Mar 29, 2019 at 20:38 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/96_

----

would it be possible for you to host yarn as a web page?
perhaps on github pages?

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Thursday Apr 04, 2019 at 12:53 GMT_

----

it will take a bit of work,but I think it's possible yes :)

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Monday Jul 29, 2019 at 15:21 GMT_

----

Yarn is hostable, however loading/saving functionality is broken since it relies on nwjs to work.

I can submit a PR to fix that in the nwjs version of yarn. It would take a bit more work to convert the electron version to a webapp, since it relies on converting to webpack. This is not a problem in the njs version because its not using nwm to fetch libraries- they are all statically copied to libs

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Monday Jul 29, 2019 at 17:37 GMT_

----

wish granted :)
@charblar or @AlecHolowka will need to enable it from this git repo's settings in order to make it go live at:
https://InfiniteAmmoInc.github.io/Yarn/app/

meanwhile, you can use it at my fork here
https://blurymind.github.io/Yarn/app/

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Monday Sep 16, 2019 at 18:03 GMT_

----

I read news of @InfiniteAmmoInc passing away, so it is unsure if anyone has access to the settings of this repository. I will continue to develop and maintain yarn here, but I have no access to the settings of the repository, so no way of hosting yarn on it - due to the need to enable hosting from the settings page

**Comment by desplesda** [comment]
<a href="https://github.com/charblar"><img src="https://avatars0.githubusercontent.com/u/25385583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [charblar](https://github.com/charblar)**
_Monday Sep 16, 2019 at 18:20 GMT_

----

@blurymind Hi, I helped Alec maintain the repository but I no longer have admin access. I would recommend forking and continuing your great work where you have admin access if you wish to continue to peruse hosting Yarn.

**Comment by blurymind** [comment]
yarn is now hosted here:
https://yarnspinnertool.github.io/YarnEditor/
We can close this bug :)
